# MySQL Database Credentials
Host: 0.0.0.0
Port: "3306"
User: username
Password: password
Database: dbname
TableName: dbbungeebot

# Create a Discord Application and add a 'BOT' user to get your bot token
# https://discordapp.com/developers/applications/
BotToken: discord_bot_token
# Enclose the prefix in parentheses "!" as some common command prefixes are considered special characters
CommandPrefix: "!"
AddMeCommand: addme

# If CheckRole is true a joining player MUST have the RequiredRoleId to be able to join
# If CheckRole is false the player will still needs to be a member of the Discord to be able to join
CheckRole: true
RequiredRoleId: "12345678987654321"

# The kick message displayed to a player that is not in the database and does not have bypass permissions
KickMessage: You are either not a member of the Discord or have not yet verified your account!